// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idktrjstyubprinrdrcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlka3RyanN0eXVicHJpbnJkcmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NzI2ODgsImV4cCI6MjA2MDA0ODY4OH0.RVsqUmewe8jS6ub57TRnXTu6ItR7CPKySYiKCFOD6_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);